// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UCG.Service.Avaliacao.Data;

#nullable disable

namespace ucg_avaliacao.Server.Migrations
{
    [DbContext(typeof(UcgAvaliacaoDbContext))]
    [Migration("20240718131031_Pessoa_Dependentes")]
    partial class Pessoa_Dependentes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UCG.Service.Avaliacao.Models.DependenteModel", b =>
                {
                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDependente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DependenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPessoa", "IdDependente");

                    b.HasIndex("DependenteId");

                    b.HasIndex("PessoaId");

                    b.ToTable("dependente", "dbo");
                });

            modelBuilder.Entity("UCG.Service.Avaliacao.Models.PessoaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("pessoa", "dbo");
                });

            modelBuilder.Entity("UCG.Service.Avaliacao.Models.DependenteModel", b =>
                {
                    b.HasOne("UCG.Service.Avaliacao.Models.PessoaModel", "Dependente")
                        .WithMany()
                        .HasForeignKey("DependenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UCG.Service.Avaliacao.Models.PessoaModel", "Pessoa")
                        .WithMany("Dependentes")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Dependente");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("UCG.Service.Avaliacao.Models.PessoaModel", b =>
                {
                    b.Navigation("Dependentes");
                });
#pragma warning restore 612, 618
        }
    }
}
