// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UCG.Service.Avaliacao.Data;

#nullable disable

namespace ucg_avaliacao.Server.Migrations
{
    [DbContext(typeof(UcgAvaliacaoDbContext))]
    [Migration("20240718202722_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UCG.Service.Avaliacao.Models.DependenteModel", b =>
                {
                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDependente")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPessoa", "IdDependente");

                    b.HasIndex("IdDependente");

                    b.ToTable("dependente", "dbo");
                });

            modelBuilder.Entity("UCG.Service.Avaliacao.Models.PessoaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RG")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("pessoa", "dbo");
                });

            modelBuilder.Entity("UCG.Service.Avaliacao.Models.DependenteModel", b =>
                {
                    b.HasOne("UCG.Service.Avaliacao.Models.PessoaModel", "Pessoa")
                        .WithMany("Dependentes")
                        .HasForeignKey("IdDependente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("UCG.Service.Avaliacao.Models.PessoaModel", b =>
                {
                    b.Navigation("Dependentes");
                });
#pragma warning restore 612, 618
        }
    }
}
